services:
  postgres:
    image: postgres:17
    container_name: kibaops_postgres
    restart: unless-stopped
    ports:
      - "5932:5432"
    environment:
      POSTGRES_DB: kibaops
      POSTGRES_USER: kibaops_user
      POSTGRES_PASSWORD: kibaops_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_DATABASE: kibaops
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro
    networks:
      - kibaops_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kibaops_user -d kibaops"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: kibaops_redis
    restart: unless-stopped
    ports:
      - "6979:6379"
    command: redis-server --appendonly yes --requirepass kibaops_redis_password
    volumes:
      - redis_data:/data
    networks:
      - kibaops_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  vault:
    image: hashicorp/vault:1.15
    container_name: kibaops_vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - kibaops_network
    healthcheck:
      test: ["CMD", "sh", "-c", "VAULT_ADDR=http://127.0.0.1:8200 vault status"]
      interval: 10s
      timeout: 5s
      retries: 5

  vault-setup:
    image: hashicorp/vault:1.15
    container_name: kibaops_vault_setup
    depends_on:
      vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: myroot
      VAULT_READ_SECRET_ID: 7c4a2e8f-9b1d-4a3c-8e5f-2d7b9c1a4e6f
      VAULT_WRITE_SECRET_ID: 3f8e1c9a-5d2b-4e7f-9a1c-6b8d4f2e7a9c
    volumes:
      - ./scripts/services/vault.sh:/vault-setup.sh:ro
    networks:
      - kibaops_network
    command: ["sh", "/vault-setup.sh"]
    restart: "no"

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=fully-notable-fowl.ngrok-free.app"
      - "host.docker.internal:8000"
    ports:
      - "4040:4040"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  kibaops_network:
    driver: bridge
