name: Frontend Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check TypeScript types
      run: npm run typecheck

    - name: Build frontend
      run: npm run build