name: Frontend Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-typecheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        coverage: none

    - name: Install PHP dependencies
      run: composer install --no-interaction --no-progress --prefer-dist

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Node.js dependencies
      run: npm ci

    - name: Check TypeScript types
      run: npm run typecheck

    - name: Build frontend
      run: npm run build